CREATE TABLE IF NOT EXISTS `USERS` (
  `id` INTEGER NOT NULL AUTO_INCREMENT ,
  `email` VARCHAR(50) NULL DEFAULT NULL ,
  `name` VARCHAR(50) NULL DEFAULT NULL ,
  `password` VARCHAR(50) NULL DEFAULT NULL ,
  `createdAt` TIMESTAMP ,
  `oauthToken` LONGTEXT NULL DEFAULT NULL ,
  PRIMARY KEY (`id`)
);

CREATE TABLE IF NOT EXISTS `CLASSROOMS` (
  `id` INTEGER NOT NULL AUTO_INCREMENT ,
  `name` VARCHAR(50) NULL DEFAULT NULL ,
  PRIMARY KEY (`id`)
);

CREATE TABLE IF NOT EXISTS `NOTES` (
  `id` INTEGER NOT NULL AUTO_INCREMENT ,
  `attachment` LONGTEXT NULL DEFAULT NULL ,
  `createdAt` TIMESTAMP ,
  `user_id` INTEGER NOT NULL ,
  `classroom_id` INTEGER NOT NULL  ,
  PRIMARY KEY (`id`) ,
  FOREIGN KEY (`user_id`) REFERENCES USERS(`id`) ,
  FOREIGN KEY (`classroom_id`) REFERENCES CLASSROOMS(`id`)
);

CREATE TABLE IF NOT EXISTS `SAVED` (
  `id` INTEGER NOT NULL AUTO_INCREMENT ,
  PRIMARY KEY (`id`)
);

CREATE TABLE IF NOT EXISTS `CLASS-USERS-JOIN` (
  `id` INTEGER NOT NULL AUTO_INCREMENT ,
  `user_id` INTEGER NOT NULL ,
  `classroom_id` INTEGER NOT NULL ,
  PRIMARY KEY (`id`) ,
  FOREIGN KEY (`user_id`) REFERENCES USERS(`id`) ,
  FOREIGN KEY (`classroom_id`) REFERENCES CLASSROOMS(`id`)
);

CREATE TABLE IF NOT EXISTS `TAG-NOTES-JOIN` (
  `id` INTEGER NOT NULL AUTO_INCREMENT ,
  `tag_id` INTEGER NOT NULL ,
  `note_id` INTEGER NOT NULL ,
  PRIMARY KEY (`id`) ,
  FOREIGN KEY (`tag_id`) REFERENCES TAGS(`id`) ,
  FOREIGN KEY (`note_id`) REFERENCES NOTES(`id`)
);

CREATE TABLE IF NOT EXISTS `SAVED-NOTES-JOIN` (
  `id` INTEGER NOT NULL AUTO_INCREMENT ,
  `saved_id` INTEGER NOT NULL ,
  `note_id` INTEGER NOT NULL ,
  PRIMARY KEY (`id`) ,
  FOREIGN KEY (`saved_id`) REFERENCES SAVED(`id`) ,
  FOREIGN KEY (`note_id`) REFERENCES NOTES(`id`)
);

CREATE TABLE IF NOT EXISTS `TAGS` (
  `id` INTEGER NOT NULL AUTO_INCREMENT ,
  `name` VARCHAR(50) NULL DEFAULT NULL ,
  PRIMARY KEY (`id`)
);

